name: CI Workflow
on:
  pull_request:
    branches:
      - master
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting with Prettier
        run: npx prettier --check .

  check-tests:
    runs-on: ubuntu-latest
    needs: check-formatting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
